// Mocks generated by Mockito 5.3.2 from annotations
// in pokedex/test/data/usecases/load_pokemon_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/domain/entities/entities.dart' as _i2;
import 'package:pokedex/domain/usecases/load_pokemon_list.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListEntity_0 extends _i1.SmartFake
    implements _i2.PokemonListEntity {
  _FakePokemonListEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadPokemonList].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadPokemonList extends _i1.Mock implements _i3.LoadPokemonList {
  @override
  _i4.Future<_i2.PokemonListEntity> fetch() => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
        ),
        returnValue:
            _i4.Future<_i2.PokemonListEntity>.value(_FakePokemonListEntity_0(
          this,
          Invocation.method(
            #fetch,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PokemonListEntity>.value(_FakePokemonListEntity_0(
          this,
          Invocation.method(
            #fetch,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PokemonListEntity>);
}
