// Mocks generated by Mockito 5.3.2 from annotations
// in pokedex/test/data/usecases/load_pokemon_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/domain/entities/entities.dart' as _i4;
import 'package:pokedex/domain/usecases/load_pokemon_details.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoadPokemonDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadPokemonDetails extends _i1.Mock
    implements _i2.LoadPokemonDetails {
  @override
  _i3.Future<List<_i4.PokemonDetailsEntity>> fetch(List<String>? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [url],
        ),
        returnValue: _i3.Future<List<_i4.PokemonDetailsEntity>>.value(
            <_i4.PokemonDetailsEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.PokemonDetailsEntity>>.value(
                <_i4.PokemonDetailsEntity>[]),
      ) as _i3.Future<List<_i4.PokemonDetailsEntity>>);
}
