// Mocks generated by Mockito 5.3.2 from annotations
// in pokedex/test/presentation/presenters/stream_pokemon_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/domain/entities/pokemon_entity.dart' as _i4;
import 'package:pokedex/domain/usecases/usecases.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoadPokemonList_0 extends _i1.SmartFake
    implements _i2.LoadPokemonList {
  _FakeLoadPokemonList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoadPokemonDetails_1 extends _i1.SmartFake
    implements _i2.LoadPokemonDetails {
  _FakeLoadPokemonDetails_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadPokemon].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadPokemon extends _i1.Mock implements _i2.LoadPokemon {
  @override
  _i2.LoadPokemonList get loadList => (super.noSuchMethod(
        Invocation.getter(#loadList),
        returnValue: _FakeLoadPokemonList_0(
          this,
          Invocation.getter(#loadList),
        ),
        returnValueForMissingStub: _FakeLoadPokemonList_0(
          this,
          Invocation.getter(#loadList),
        ),
      ) as _i2.LoadPokemonList);
  @override
  _i2.LoadPokemonDetails get loadDetails => (super.noSuchMethod(
        Invocation.getter(#loadDetails),
        returnValue: _FakeLoadPokemonDetails_1(
          this,
          Invocation.getter(#loadDetails),
        ),
        returnValueForMissingStub: _FakeLoadPokemonDetails_1(
          this,
          Invocation.getter(#loadDetails),
        ),
      ) as _i2.LoadPokemonDetails);
  @override
  _i3.Future<List<_i4.PokemonEntity>> fetch({String? nextUrl}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [],
          {#nextUrl: nextUrl},
        ),
        returnValue:
            _i3.Future<List<_i4.PokemonEntity>>.value(<_i4.PokemonEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.PokemonEntity>>.value(<_i4.PokemonEntity>[]),
      ) as _i3.Future<List<_i4.PokemonEntity>>);
}
